### ISSUE TITLE
Build versions published since 20.9

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/ambertools-feedstock#52]
List of pending patches:

- [x] 20.9 - check #50 - [CI report](https://github.com/conda-forge/ambertools-feedstock/runs/1682807002)
- [x] 20.10 - check #53 - [CI report](https://github.com/conda-forge/ambertools-feedstock/runs/1682806060)
- [x] 20.11 - check #54 - [CI report](https://github.com/conda-forge/ambertools-feedstock/runs/1682802160)
- [x] 20.12 - check #55 - [CI report](https://github.com/conda-forge/ambertools-feedstock/runs/1686577076)
- [x] 20.13 - check #56 - [CI report](https://github.com/conda-forge/ambertools-feedstock/runs/1694069285)
- [x] 20.14 - check #57 - [CI report](https://github.com/conda-forge/ambertools-feedstock/runs/1697595602)

Note that the PPC builds time out very often so it's tricky to get them uploaded. Many retries needed. If you don't see a particular package online, check the CI report for that version.

**Comment by jaimergp** [comment]
I will work on this once #50 is published
